////////////////////////////////////////////////////////////////////////////////
// Data Structures and Algorithms - Homework 4                                //
// hw4_1.cpp                                                                  //
// The main functions                                                         //
//                                                                            //
// Author: emfo<emfomy@gmail.com>                                             //
////////////////////////////////////////////////////////////////////////////////

#include <iostream>
#include <fstream>
#include <iomanip>
#include "hw4.hpp"
#include "sample_set.hpp"
#include "tree.hpp"
using namespace hw4;
using namespace std;

////////////////////////////////////////////////////////////////////////////////
// Main function                                                              //
////////////////////////////////////////////////////////////////////////////////
int main( int argc, char *argv[] ) {
  SampleSet set;
  ifstream fin;
  const string output_name = "tree_predict";
  double tolerance = (argc > 2) ? atof(argv[2]) : 0.0;
  const char* str_tol = (argc > 2) ? argv[2] : "0.0";

  ios::sync_with_stdio(false);

  // Load sample set from file
  fin.open(argv[1]);
  fin >> set;
  fin.close();

  // Create tree
  Tree tree(set, tolerance);

  // Display file comments
  cout << setw(80) << setfill('/')
       << "" << endl;
  cout << setw(78) << left << setfill(' ')
       << "// Data Structures and Algorithms - Homework 4" << "//" << endl;
  cout << setw(78) << left << setfill(' ')
       << "// "+output_name+".cpp" << "//" << endl;
  cout << setw(78) << left << setfill(' ')
       << "// A decision tree generated by '"+string(argv[0])+"'" << "//" << endl;
  cout << setw(78) << left << setfill(' ')
       << "//   trained by '"+string(argv[1])+
          "' with tolerance="+string(str_tol) << "//" << endl;
  cout << setw(78) << setfill(' ')
       << "// " << "//\n";
  cout << setw(78) << left << setfill(' ')
       << "// Author: emfo<emfomy@gmail.com>" << "//" << endl;
  cout << setw(80) << setfill('/')
       << "" << endl << endl;

  // Display includes
  cout << "#include <cstdlib>" << endl;
  cout << "#include <ctime>" << endl << endl;

  // Display main function comments
  cout << setw(80) << setfill('/')
       << "" << endl;
  cout << setw(78) << left << setfill(' ')
       << "// Tree predict" << "//" << endl;
  cout << setw(78) << setfill(' ')
       << "// " << "//\n";
  cout << setw(78) << left << setfill(' ')
       << "// Parameters:" << "//" << endl;
  cout << setw(78) << left << setfill(' ')
       << "// The features of a sample" << "//" << endl;
  cout << setw(78) << setfill(' ')
       << "// " << "//\n";
  cout << setw(78) << left << setfill(' ')
       << "// Return Value:" << "//" << endl;
  cout << setw(78) << left << setfill(' ')
       << "// The predicted label of this sample" << "//" << endl;
  cout << setw(80) << setfill('/')
       << "" << endl;

  // Display main function
  cout << "int tree_predict( double *attr ) {" << endl;
  cout << "  // Initialize random seed" << endl;
  cout << "  srand(time(NULL));" << endl << endl;
  cout << "  // Predict response using decision tree" << endl;
  tree.Print(1);
  cout << "}" << endl << endl;

  return 0;
}
